### ISSUE TITLE
Notices from MPDF seem to lead to exceptions

### ISSUE THREAD

**Issue by amenk** [niklasravnsborg/laravel-pdf#168]
**Describe the bug**

Upon certain HTML, MPDF generates a notice (see https://github.com/mpdf/mpdf/issues/853 ) which seems to lead to crashes.

	[2020-06-05 14:08:57] production.ERROR: Undefined index: list_style_type (ErrorException(code: 0): Undefined index: list_style_type at /var/www/example/vendor/mpdf/mpdf/src/Tag/BlockTag.php:898)
	[stacktrace]
	#0 /var/www/example/vendor/mpdf/mpdf/src/Tag/BlockTag.php(898): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/intran...', 898, Array)
	#1 /var/www/example/vendor/mpdf/mpdf/src/Tag.php(243): Mpdf\\Tag\\BlockTag->open(Array, Array, 357)
	#2 /var/www/example/vendor/mpdf/mpdf/src/Mpdf.php(13634): Mpdf\\Tag->OpenTag('LI', Array, Array, 357)
	#3 /var/www/example/vendor/niklasravnsborg/laravel-pdf/src/LaravelPdf/Pdf.php(57): Mpdf\\Mpdf->WriteHTML(' <div class=\"co...')
	#4 /var/www/example/vendor/niklasravnsborg/laravel-pdf/src/LaravelPdf/PdfWrapper.php(42): niklasravnsborg\\LaravelPdf\\Pdf->__construct('<style>\

**To Reproduce**
1. Use faulty HTML
2. Laravel crashes
3. See error

**Expected behavior**
PDF is still generated, even in case of not 100% valid HTML

Not sure if this an issue of Laravel-PDF or MPDF. Feedback welcome how to solve this properly. Maybe we just have to lower the error reporting level?

**Comment by niklasravnsborg** [comment]
@amenk Hey, I‘m pretty sure this is an issue of mpdf. Can you provide some faulty HTML that leads to the crashes on your side?

**Comment by amenk** [comment]
<ul><div><li>Test</li></div></ul>

 But I did not yet verify this as isolated example

**Comment by amenk** [comment]
Steps to reproduce in a fresh Laravel 7.12 project, with laravel-pdf ^4.0

user@computer:~/example/projects$ composer create-project --prefer-dist laravel/laravel laravel-pdf-test
Creating a "laravel/laravel" project at "./laravel-pdf-test"
Installing laravel/laravel (v7.12.0)
...

user@computer:~/example/projects$ composer require niklasravnsborg/laravel-pdf
Using version ^4.0 for niklasravnsborg/laravel-pdf

...

no replace `resources/views/welcome.blade.php` with

     <ul><div><li>Test</li></div></ul>



replace `routes/web.php` with

	<?php

	use Illuminate\Support\Facades\Route;
	use PDF;

	Route::get('/', function () {
	    $pdf = PDF::loadView('welcome', []);
	    return $pdf->stream('document.pdf');

	});


Open `/`

This is thrown

    ErrorException
    Undefined index: list_style_type

At MPDF they claim this is just a notice and not a crash, but when using in Laravel-PDF, it crashes.

Might be because of Laravel's error reporting levels?

![error](https://user-images.githubusercontent.com/1087128/84986625-2630a680-b13f-11ea-8d2c-ddca4127e198.png)

**Comment by amenk** [comment]
@niklasravnsborg How shall we proceed here? Can we catch the exception somehow?

**Comment by niklasravnsborg** [comment]
Unfortunately I'm currently not available to investigate further. Maybe you find the cause and provide a fix via pull request?

Niklas

**Comment by repouniverse** [comment]
The same thing happens to me in Yii2, I'm desperate, I can't find the solution, the worst thing is that there is no literature in the wen about this. I'm sure it's a Mpdf bug.

**Comment by slefevre** [comment]
This has given me a bit of a hiccup. I'm using a WYSIWYG editor to allow users to edit chapter text. The resulting content is wrapped in a div, and I believe the user can add divs, also. 

Chapters are presented to the end-user enumerated; `<ol>` is the easiest way to get automatic numbering. After finding out that divs in ol tags are not allowed, I tried switching to css counter, but it appears that mpdf doesn't recognize css counter properties. 

Finally I settled on adding the count to the content itself. This would seem to break the principle of separating content from presentation.

**Comment by vpsbohra** [comment]
I'm facing the same issue but for Undefined Index : SELECT

**Comment by pourmami** [comment]
I was getting this error and fixed it by removing the CSS classes of all <td> and <th>s

**Comment by pourmami** [comment]
I used hex color `(#FFFFFF)` instead of `rgb(31 41 55 / var(--tw-border-opacity))` and fixed this error
![image](https://user-images.githubusercontent.com/66114909/179395754-71862c88-4aa7-41a0-bca4-dc5290303a05.png)
